// Ported from dsh-ios (MIT, © 2026 ZSeven—W) @ d9a9731 — assets/preview-host/PreviewHostApp.swift
import SwiftUI

/// Disposable SwiftUI preview host generated by the ios-simulator plugin. It runs
/// inside the simulator, polls a drop directory for hot-swapped preview
/// dylibs, dlopens them and shows the current preview without relaunching.
///
/// Architecture note: this host follows the publicly documented approach of
/// the Codex `ios-simulator-browser` skill (a disposable host app outside
/// the user's source tree + a watched, hot-swapped preview dylib).
/// github.com/openai/plugins ships without a license, so this implementation
/// was written from the architectural description — no Codex code was copied.
@main
struct PreviewHostApp: App {
  @StateObject private var session = PreviewSession()

  var body: some Scene {
    WindowGroup {
      PreviewRootView(session: session)
    }
  }
}
