// Regenerates the "Bundled into dist/" part of THIRD_PARTY_NOTICES.md: every npm package that esbuild's
// metafile shows inside dist/server.js or dist/panel/main.js, with the license text from its LICENSE file.
// The hand-written sections above the marker are kept as they are. Usage: npm run notices
import { build } from 'esbuild'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { panelBundle, root, serverBundle } from './bundles.mjs'

const NOTICES = join(root, 'THIRD_PARTY_NOTICES.md')
const MARKER = '<!-- Everything below is generated by `npm run notices` from the esbuild metafiles; do not edit it by hand. -->'
const BUNDLES = [['dist/server.js', serverBundle], ['dist/panel/main.js', panelBundle]]

/** `node_modules/<name>/…` or `node_modules/@scope/<name>/…` → that package's directory (innermost node_modules). */
function packageDirOf(input) {
  const at = input.lastIndexOf('node_modules/')
  if (at < 0) return undefined
  const [first = '', second = ''] = input.slice(at + 'node_modules/'.length).split('/')
  return `${input.slice(0, at)}node_modules/${first.startsWith('@') ? `${first}/${second}` : first}`
}

/** Package directories (relative to the repo root) whose files esbuild put into one bundle. */
async function bundledPackageDirs(options) {
  const { metafile } = await build({ ...options, write: false, metafile: true, absWorkingDir: root })
  return new Set(Object.keys(metafile.inputs).map(packageDirOf).filter(dir => dir !== undefined))
}

function licenseText(dir) {
  const file = readdirSync(join(root, dir)).find(name => /^(licen[cs]e|copying)(\.(md|txt))?$/iu.test(name))
  if (file === undefined) throw new Error(`${dir} ships no LICENSE file — add its license text by hand`)
  const text = readFileSync(join(root, dir, file), 'utf8').trim()
  if (text.includes('~~~')) throw new Error(`${dir}/${file} contains ~~~, which would break its fence`)
  return text
}

const packages = new Map()
for (const [label, options] of BUNDLES) {
  for (const dir of await bundledPackageDirs(options)) {
    const manifest = JSON.parse(readFileSync(join(root, dir, 'package.json'), 'utf8'))
    const entry = packages.get(dir) ?? {
      name: manifest.name,
      version: manifest.version,
      license: typeof manifest.license === 'string' ? manifest.license : manifest.license?.type ?? 'see the license text',
      text: licenseText(dir),
      bundles: [],
    }
    entry.bundles.push(label)
    packages.set(dir, entry)
  }
}
const sorted = [...packages.values()].sort((a, b) => a.name.localeCompare(b.name))

const lines = ['## Bundled into dist/', '']
for (const [label] of BUNDLES) {
  const count = sorted.filter(entry => entry.bundles.includes(label)).length
  lines.push(count === 0
    ? `- \`${label}\` bundles no third-party packages, only this plugin's own code.`
    : `- \`${label}\` bundles the ${count} npm package${count === 1 ? '' : 's'} listed below.`)
}
lines.push('', '| Package | Version | License | Bundled into |', '| --- | --- | --- | --- |')
for (const entry of sorted) {
  lines.push(`| ${entry.name} | ${entry.version} | ${entry.license} | ${entry.bundles.map(label => `\`${label}\``).join(', ')} |`)
}
for (const entry of sorted) lines.push('', `### ${entry.name} ${entry.version}`, '', '~~~text', entry.text, '~~~')

const current = readFileSync(NOTICES, 'utf8')
const at = current.indexOf(MARKER)
if (at < 0) throw new Error(`THIRD_PARTY_NOTICES.md lost its marker line; restore it:\n${MARKER}`)
writeFileSync(NOTICES, `${current.slice(0, at + MARKER.length)}\n\n${lines.join('\n')}\n`)
console.log(`THIRD_PARTY_NOTICES.md: ${sorted.length} bundled packages (${sorted.map(entry => entry.name).join(', ')})`)
